export type Vec3 = readonly [number, number, number];

export type EntityKind = 'core' | 'infra' | 'service' | 'channel' | 'integration' | 'ai';

export type EntityTier = 'foundation' | 'critical' | 'business' | 'edge';

export type EntityStatus = 'resilient' | 'operational' | 'observed';

export type EntityShape = 'citadel' | 'database' | 'bus' | 'lab' | 'shop' | 'tower' | 'gateway' | 'platform';

export interface TownServiceDetail {
    purpose: string;
    systemRole: string;
    flows: readonly string[];
    reliability: readonly string[];
    related: readonly string[];
}

export interface TownEntity {
    id: string;
    name: string;
    kind: EntityKind;
    tier: EntityTier;
    status: EntityStatus;
    shape: EntityShape;
    clusterId: string;
    position: Vec3;
    size: Vec3;
    color: string;
    accentColor: string;
    summary: string;
    details: TownServiceDetail;
    connections: readonly string[];
}

export interface TownDistrict {
    id: string;
    name: string;
    center: Vec3;
    radius: number;
    color: string;
    description: string;
}

export const townDistricts: readonly TownDistrict[] = [
    {
        id: 'foundation',
        name: 'Foundation Stronghold',
        center: [0, 0, 0],
        radius: 250,
        color: '#12b8a6',
        description: 'Core systems built from the ground up for durability.',
    },
    {
        id: 'ai',
        name: 'AI Trust District',
        center: [420, 0, -230],
        radius: 190,
        color: '#ffb45c',
        description: 'AI runtime, retrieval, training, and model gateway.',
    },
    {
        id: 'services',
        name: 'Service Market',
        center: [120, 0, 390],
        radius: 240,
        color: '#69b7ff',
        description: 'Operational modules businesses can enter and use.',
    },
    {
        id: 'communications',
        name: 'Unified Inbox',
        center: [-430, 0, 120],
        radius: 230,
        color: '#9ed86a',
        description: 'All customer channels flowing into one operational inbox.',
    },
    {
        id: 'integrations',
        name: 'Integration Edge',
        center: [-300, 0, -360],
        radius: 190,
        color: '#f2c56b',
        description: 'External systems, bank APIs, partners, and notification routes.',
    },
];

export const townEntities: readonly TownEntity[] = [
    {
        id: 'kaojai-core',
        name: 'KaoJai Core',
        kind: 'core',
        tier: 'foundation',
        status: 'resilient',
        shape: 'citadel',
        clusterId: 'foundation',
        position: [0, 0, 0],
        size: [82, 118, 82],
        color: '#13b8a8',
        accentColor: '#e8fffb',
        summary: 'The operational brain that connects chat, AI, workflow, and business state.',
        details: {
            purpose: 'Unifies customer conversations, automation, tenant operations, and business logic into one trusted center.',
            systemRole: 'Core logic hub for chatbot, booking, CheckSlip, alerts, admin workflows, and data coordination.',
            flows: ['Coordinates chatbot orchestration', 'Reads and writes tenant state', 'Routes events to alert and service systems'],
            reliability: ['Foundation-tier stronghold', 'Clear boundaries around critical business rules', 'Connected through evented flows instead of brittle point-to-point paths'],
            related: ['Database Cluster', 'Event Bus', 'AI Lab', 'Service Market'],
        },
        connections: ['database-cluster', 'event-bus', 'ai-engine', 'booking-management', 'checkslip'],
    },
    {
        id: 'database-cluster',
        name: 'Database Cluster',
        kind: 'infra',
        tier: 'foundation',
        status: 'resilient',
        shape: 'database',
        clusterId: 'foundation',
        position: [-150, 0, -80],
        size: [72, 105, 72],
        color: '#78d882',
        accentColor: '#d7ffe0',
        summary: 'Postgres-backed source of truth for tenants, bookings, issues, conversations, and operational state.',
        details: {
            purpose: 'Keeps the town grounded in durable business data.',
            systemRole: 'Primary relational store used by admin, booking, issue, CheckSlip, and core flows.',
            flows: ['Stores booking and issue records', 'Supports admin dashboards', 'Publishes important state changes through the event bus'],
            reliability: ['Layered vault form communicates durability', 'Close to core to show low-latency dependency', 'Monitored as a critical foundation asset'],
            related: ['KaoJai Core', 'Monitoring Tower', 'Event Bus'],
        },
        connections: ['kaojai-core', 'event-bus', 'monitoring-tower'],
    },
    {
        id: 'event-bus',
        name: 'Event Bus',
        kind: 'infra',
        tier: 'foundation',
        status: 'resilient',
        shape: 'bus',
        clusterId: 'foundation',
        position: [150, 0, -70],
        size: [90, 70, 58],
        color: '#ffd05a',
        accentColor: '#fff4bd',
        summary: 'Central routing spine for asynchronous signals, fan-out, and service coordination.',
        details: {
            purpose: 'Moves events through the town without forcing every service to know every other service directly.',
            systemRole: 'Receives signals from database, bot registration, mini app, LINE OA, and service flows.',
            flows: ['Fans results to users', 'Feeds CheckSlip notifications', 'Connects booking and channel updates'],
            reliability: ['Fortified routing bridge', 'Animated packet streams show continuous movement', 'Scale guard form highlights resilience under load'],
            related: ['KaoJai Core', 'Message Queue', 'Notification Hub'],
        },
        connections: ['kaojai-core', 'message-queue', 'notification-hub', 'booking-management'],
    },
    {
        id: 'auth-service',
        name: 'Auth Service',
        kind: 'infra',
        tier: 'critical',
        status: 'resilient',
        shape: 'gateway',
        clusterId: 'foundation',
        position: [-70, 0, 145],
        size: [58, 76, 58],
        color: '#ff8c9a',
        accentColor: '#ffe4e8',
        summary: 'Identity gate for admin dashboard, issue console, and chat console access.',
        details: {
            purpose: 'Keeps tenant operations protected before staff enter critical tools.',
            systemRole: 'Authentication boundary shared by admin-facing consoles.',
            flows: ['Verifies admin access', 'Protects issue and chat consoles', 'Separates tenant operations'],
            reliability: ['Placed inside the stronghold ring', 'Gate silhouette communicates strict entry', 'Connected to monitored admin flows'],
            related: ['KaoJai Core', 'Monitoring Tower', 'Unified Inbox'],
        },
        connections: ['kaojai-core', 'unified-inbox', 'issue-management'],
    },
    {
        id: 'monitoring-tower',
        name: 'Monitoring Tower',
        kind: 'infra',
        tier: 'critical',
        status: 'observed',
        shape: 'tower',
        clusterId: 'foundation',
        position: [125, 0, 135],
        size: [52, 116, 52],
        color: '#d9dde7',
        accentColor: '#6cc9ff',
        summary: 'Observability tower watching logs, workers, service health, and delivery paths.',
        details: {
            purpose: 'Makes reliability visible instead of hidden behind the scenes.',
            systemRole: 'Represents logs shipper, logs storage, and monitoring dashboard.',
            flows: ['Receives worker logs', 'Surfaces operational health', 'Watches message and campaign delivery paths'],
            reliability: ['Beacon and scan rings make health status visible', 'Located beside core systems', 'Supports fast diagnosis when flows degrade'],
            related: ['Database Cluster', 'Broadcast Campaigns', 'Message Queue'],
        },
        connections: ['database-cluster', 'broadcast-campaigns', 'message-queue'],
    },
    {
        id: 'object-storage',
        name: 'Object Storage',
        kind: 'infra',
        tier: 'critical',
        status: 'resilient',
        shape: 'platform',
        clusterId: 'foundation',
        position: [-230, 0, 80],
        size: [70, 64, 70],
        color: '#cfd8e8',
        accentColor: '#ffffff',
        summary: 'Storage platform for static site assets, backups, and user content.',
        details: {
            purpose: 'Holds durable files that support the product beyond live request flow.',
            systemRole: 'Object storage and image transformation support for content and backups.',
            flows: ['Serves static assets', 'Stores backups', 'Feeds dynamic image transformation'],
            reliability: ['Raised storage blocks communicate redundancy', 'Near core but off the main road to preserve whitespace', 'Connected to monitoring for operational visibility'],
            related: ['Image Server', 'Monitoring Tower'],
        },
        connections: ['image-server', 'monitoring-tower'],
    },
    {
        id: 'image-server',
        name: 'Image Server',
        kind: 'infra',
        tier: 'business',
        status: 'operational',
        shape: 'tower',
        clusterId: 'foundation',
        position: [-315, 0, 125],
        size: [42, 62, 42],
        color: '#9cc9ff',
        accentColor: '#eaf4ff',
        summary: 'Dynamic transformation service for product and user content images.',
        details: {
            purpose: 'Makes stored media usable in the right size and format for product surfaces.',
            systemRole: 'Lambda-style transformation service in front of object storage.',
            flows: ['Reads source content', 'Transforms images for delivery', 'Supports public product assets'],
            reliability: ['Small service tower connected to object storage', 'Kept separate from critical core logic', 'Observed by the monitoring district'],
            related: ['Object Storage', 'Monitoring Tower'],
        },
        connections: ['object-storage', 'monitoring-tower'],
    },
    {
        id: 'ai-engine',
        name: 'AI Engine',
        kind: 'ai',
        tier: 'critical',
        status: 'resilient',
        shape: 'lab',
        clusterId: 'ai',
        position: [420, 0, -230],
        size: [88, 112, 88],
        color: '#ffb25e',
        accentColor: '#fff0d6',
        summary: 'AI foundation powering triage, answers, slot filling, and guided business workflows.',
        details: {
            purpose: 'Turns conversational input into useful operational actions for Thai businesses.',
            systemRole: 'AI runtime connected to RAG, training, fine-tuning, and model gateway.',
            flows: ['Provides intelligence to mini app and chatbot', 'Uses knowledge retrieval', 'Supports tool and function-call decisions'],
            reliability: ['Glass lab with protected runtime core', 'Separated from core but connected by a reinforced bridge', 'Stable runtime highlighted as a first-class asset'],
            related: ['KaoJai Core', 'RAG Library', 'LLM Gateway'],
        },
        connections: ['kaojai-core', 'rag-library', 'llm-gateway', 'training-yard', 'fine-tuning-bay'],
    },
    {
        id: 'rag-library',
        name: 'RAG Library',
        kind: 'ai',
        tier: 'business',
        status: 'operational',
        shape: 'platform',
        clusterId: 'ai',
        position: [305, 0, -150],
        size: [60, 58, 60],
        color: '#ffcf86',
        accentColor: '#fff8e8',
        summary: 'Knowledge base that lets AI answer with business-specific context.',
        details: {
            purpose: 'Keeps answers grounded in tenant knowledge instead of generic responses.',
            systemRole: 'Retrieval support for FAQ, knowledge, and AI chat flows.',
            flows: ['Stores knowledge references', 'Feeds AI answer context', 'Connects FAQ knowledge to chat'],
            reliability: ['Library stacks show curated knowledge', 'Close to AI engine for clear dependency', 'Connected to FAQ shop for visitor understanding'],
            related: ['AI Engine', 'FAQ / Knowledge'],
        },
        connections: ['ai-engine', 'faq-knowledge'],
    },
    {
        id: 'training-yard',
        name: 'Training Yard',
        kind: 'ai',
        tier: 'business',
        status: 'operational',
        shape: 'platform',
        clusterId: 'ai',
        position: [525, 0, -145],
        size: [58, 54, 58],
        color: '#ff9c66',
        accentColor: '#ffe6d8',
        summary: 'Training area for improving AI behavior and domain readiness.',
        details: {
            purpose: 'Represents the workbench where AI capability improves over time.',
            systemRole: 'Training component in the AI foundation.',
            flows: ['Feeds improved model behavior', 'Supports evaluation of tenant use cases', 'Improves automation readiness'],
            reliability: ['Placed beside but not inside runtime', 'Shows separation between build-time learning and live serving', 'Supports scalable AI operations'],
            related: ['AI Engine', 'Fine-tuning Bay'],
        },
        connections: ['ai-engine', 'fine-tuning-bay'],
    },
    {
        id: 'fine-tuning-bay',
        name: 'Fine-tuning Bay',
        kind: 'ai',
        tier: 'business',
        status: 'operational',
        shape: 'platform',
        clusterId: 'ai',
        position: [545, 0, -315],
        size: [58, 54, 58],
        color: '#f48a5f',
        accentColor: '#ffe3d5',
        summary: 'Controlled bay for specializing AI behavior without mixing concerns into runtime.',
        details: {
            purpose: 'Shows model improvement as a managed capability.',
            systemRole: 'Fine-tuning component inside the AI foundation.',
            flows: ['Receives training signals', 'Supports specialized assistants', 'Hands improved capability back to AI runtime'],
            reliability: ['Separate bay prevents runtime confusion', 'Close to training and LLM gateway', 'Designed as a scalable AI support module'],
            related: ['AI Engine', 'Training Yard', 'LLM Gateway'],
        },
        connections: ['ai-engine', 'training-yard', 'llm-gateway'],
    },
    {
        id: 'llm-gateway',
        name: 'LLM Gateway',
        kind: 'ai',
        tier: 'edge',
        status: 'operational',
        shape: 'gateway',
        clusterId: 'ai',
        position: [410, 0, -395],
        size: [58, 76, 58],
        color: '#ffc25f',
        accentColor: '#fff0ca',
        summary: 'Gateway to model providers used as part of the AI foundation.',
        details: {
            purpose: 'Keeps third-party model access explicit and controlled.',
            systemRole: 'External LLM model boundary used by the AI engine.',
            flows: ['Receives model requests', 'Returns generated intelligence', 'Keeps provider dependency outside core business state'],
            reliability: ['Gateway form communicates boundary control', 'Not placed inside foundation stronghold', 'AI engine remains the owned orchestration point'],
            related: ['AI Engine', 'Fine-tuning Bay'],
        },
        connections: ['ai-engine', 'fine-tuning-bay'],
    },
    {
        id: 'booking-management',
        name: 'Booking Management',
        kind: 'service',
        tier: 'business',
        status: 'operational',
        shape: 'shop',
        clusterId: 'services',
        position: [30, 0, 350],
        size: [68, 58, 68],
        color: '#66b8ff',
        accentColor: '#e7f5ff',
        summary: 'Real-time availability, confirmations, reminders, reschedules, and partner booking sync.',
        details: {
            purpose: 'Lets businesses manage bookings from chat into real operational schedules.',
            systemRole: 'Booking skill, allotment queue, consumer, and availability query flow.',
            flows: ['Checks available allotment', 'Creates and updates bookings', 'Keeps partner booking and sales information aligned'],
            reliability: ['Connected to queue and database', 'Availability ring shows real-time checks', 'Search and summary surfaces reduce operational friction'],
            related: ['KaoJai Core', 'Database Cluster', 'Event Bus'],
        },
        connections: ['kaojai-core', 'database-cluster', 'event-bus', 'partner-exchange'],
    },
    {
        id: 'issue-management',
        name: 'Issue Management',
        kind: 'service',
        tier: 'business',
        status: 'operational',
        shape: 'shop',
        clusterId: 'services',
        position: [120, 0, 460],
        size: [64, 54, 64],
        color: '#8cc8ff',
        accentColor: '#e7f5ff',
        summary: 'AI triage and issue tracking with missing-info collection and status updates.',
        details: {
            purpose: 'Turns messy customer messages into structured operational follow-up.',
            systemRole: 'Issue management tool connected to core logic and database.',
            flows: ['Collects missing details', 'Creates issue records', 'Notifies status changes through messaging'],
            reliability: ['Issue shop sits near booking for shared operations', 'Database connection is explicit', 'Designed for human handoff when automation is not enough'],
            related: ['Unified Inbox', 'KaoJai Core', 'Database Cluster'],
        },
        connections: ['kaojai-core', 'database-cluster', 'unified-inbox'],
    },
    {
        id: 'faq-knowledge',
        name: 'FAQ / Knowledge',
        kind: 'service',
        tier: 'business',
        status: 'operational',
        shape: 'shop',
        clusterId: 'services',
        position: [235, 0, 390],
        size: [62, 52, 62],
        color: '#73c4ff',
        accentColor: '#e9f7ff',
        summary: 'Knowledge shop that supports reliable AI answers and reusable business information.',
        details: {
            purpose: 'Keeps common answers reusable instead of manually repeated by staff.',
            systemRole: 'FAQ and knowledge skill used by chatbot orchestration and RAG.',
            flows: ['Stores reusable answers', 'Feeds AI responses', 'Reduces repeated manual replies'],
            reliability: ['Linked directly to RAG library', 'Separated from AI runtime to keep content ownership clear', 'Simple shop form makes it easy for visitors to understand'],
            related: ['RAG Library', 'Chatbot Orchestration'],
        },
        connections: ['rag-library', 'chatbot-orchestration'],
    },
    {
        id: 'checkslip',
        name: 'CheckSlip',
        kind: 'service',
        tier: 'business',
        status: 'resilient',
        shape: 'shop',
        clusterId: 'services',
        position: [235, 0, 520],
        size: [66, 56, 66],
        color: '#ffb36d',
        accentColor: '#fff0df',
        summary: 'Thai bank slip verification with duplicate detection and notification routing.',
        details: {
            purpose: 'Protects businesses from manual payment checking and duplicate slip risk.',
            systemRole: 'CheckSlip queue, consumer, validator, bank API call, and verification notifier.',
            flows: ['Consumes slip verification jobs', 'Checks duplicate and validity signals', 'Notifies users of success or failure'],
            reliability: ['Scanner gate and duplicate seal emphasize fraud prevention', 'Bank API is outside the town edge', 'Notifier path makes error handling visible'],
            related: ['Bank API', 'Notification Hub', 'KaoJai Core'],
        },
        connections: ['kaojai-core', 'bank-api', 'notification-hub'],
    },
    {
        id: 'billing-pricing',
        name: 'Billing & Pricing',
        kind: 'service',
        tier: 'business',
        status: 'operational',
        shape: 'shop',
        clusterId: 'services',
        position: [-70, 0, 470],
        size: [62, 52, 62],
        color: '#5cc9d6',
        accentColor: '#ddfbff',
        summary: 'Plan, usage, subscription, top-up, and invoice automation experience.',
        details: {
            purpose: 'Lets customers manage commercial usage without hidden manual steps.',
            systemRole: 'Billing experience for subscriptions, top-ups, plan usage, and daily invoice generation for paid plans.',
            flows: ['Shows plan and usage management', 'Supports subscriptions and top-ups', 'Generates invoices automatically when billing periods end'],
            reliability: ['No invented public pricing numbers', 'Billing station is close to service shops but separate from core logic', 'Automation reinforces operational trust'],
            related: ['KaoJai Core', 'Monitoring Tower'],
        },
        connections: ['kaojai-core', 'monitoring-tower'],
    },
    {
        id: 'broadcast-campaigns',
        name: 'Broadcast Campaigns',
        kind: 'service',
        tier: 'business',
        status: 'resilient',
        shape: 'platform',
        clusterId: 'services',
        position: [-50, 0, 590],
        size: [130, 58, 76],
        color: '#7bbdff',
        accentColor: '#fff0b8',
        summary: 'Reliable audience campaign delivery with queues, smoothing, retries, and dead-letter handling.',
        details: {
            purpose: 'Lets businesses send large-audience updates without making delivery fragile.',
            systemRole: 'Campaign composer, audience identity, delivery workers, rate smoother, retry garden, and dead-letter dock.',
            flows: ['Segments target audiences', 'Meters send rate', 'Fans out to LINE, Facebook, Instagram, and Lazada'],
            reliability: ['Retry coils and dead-letter dock make failure handling visible', 'Delivery spine shows controlled fan-out', 'Alert lens highlights operational awareness'],
            related: ['Unified Inbox', 'Message Queue', 'Monitoring Tower'],
        },
        connections: ['message-queue', 'line-channel', 'facebook-channel', 'instagram-channel', 'lazada-channel', 'monitoring-tower'],
    },
    {
        id: 'unified-inbox',
        name: 'Unified Inbox',
        kind: 'channel',
        tier: 'critical',
        status: 'operational',
        shape: 'platform',
        clusterId: 'communications',
        position: [-420, 0, 120],
        size: [96, 64, 72],
        color: '#9bdc77',
        accentColor: '#ecffe5',
        summary: 'All chat channels in one dashboard for assignment, tags, tracking, and SLA work.',
        details: {
            purpose: 'Gives tenant agents one place to manage customer conversations.',
            systemRole: 'Admin chat console connected to message queue and outbound workers.',
            flows: ['Receives channel conversations', 'Sends messages through workers', 'Supports human handoff and tracking'],
            reliability: ['Placed at the center of communication district', 'Connected to channel collectors and queue', 'Supports staff control when AI hands off'],
            related: ['LINE Channel', 'Facebook Channel', 'Instagram Channel', 'Lazada Channel', 'Message Queue'],
        },
        connections: ['line-channel', 'facebook-channel', 'instagram-channel', 'lazada-channel', 'message-queue', 'chatbot-orchestration'],
    },
    {
        id: 'chatbot-orchestration',
        name: 'Chatbot Orchestration',
        kind: 'channel',
        tier: 'critical',
        status: 'resilient',
        shape: 'tower',
        clusterId: 'communications',
        position: [-320, 0, -20],
        size: [74, 92, 74],
        color: '#8bd3ff',
        accentColor: '#e7f7ff',
        summary: 'Conversation service, triage, slot filling, and function-call coordination.',
        details: {
            purpose: 'Coordinates AI conversation behavior with operational tools.',
            systemRole: 'Chatbot orchestration layer connected to booking, issue, FAQ, fun tools, mini app, and AI engine.',
            flows: ['Routes tool calls', 'Handles triage and slot filling', 'Connects conversation service to core logic'],
            reliability: ['Tower form emphasizes control', 'Nearby AI bridge keeps intelligence visible', 'Tool connections are explicit instead of hidden'],
            related: ['AI Engine', 'Booking Management', 'Issue Management', 'FAQ / Knowledge'],
        },
        connections: ['ai-engine', 'kaojai-core', 'booking-management', 'issue-management', 'faq-knowledge'],
    },
    {
        id: 'message-queue',
        name: 'Message Queue',
        kind: 'channel',
        tier: 'critical',
        status: 'resilient',
        shape: 'bus',
        clusterId: 'communications',
        position: [-530, 0, 20],
        size: [80, 50, 60],
        color: '#ffd05a',
        accentColor: '#fff6c7',
        summary: 'Send-message queue and worker lane for reliable outbound communication.',
        details: {
            purpose: 'Buffers outbound work so user messaging stays controlled under load.',
            systemRole: 'Send message queue and worker that dispatches to chat platforms.',
            flows: ['Queues status updates', 'Feeds send worker', 'Delivers to LINE, Facebook, Instagram, and Lazada'],
            reliability: ['Queue shape shows buffering', 'Worker path connects to monitoring', 'Rate control is reinforced by broadcast district'],
            related: ['Unified Inbox', 'Broadcast Campaigns', 'Monitoring Tower'],
        },
        connections: ['unified-inbox', 'line-channel', 'facebook-channel', 'instagram-channel', 'lazada-channel', 'monitoring-tower'],
    },
    {
        id: 'line-channel',
        name: 'LINE Channel',
        kind: 'channel',
        tier: 'edge',
        status: 'operational',
        shape: 'gateway',
        clusterId: 'communications',
        position: [-575, 0, 165],
        size: [46, 56, 46],
        color: '#06c755',
        accentColor: '#dffff0',
        summary: 'LINE messaging collector and outbound route for Thai customer conversations.',
        details: {
            purpose: 'Connects the town to one of the main customer conversation surfaces.',
            systemRole: 'Messaging platform collector and outbound target.',
            flows: ['Receives user messages', 'Publishes into PubSub', 'Receives worker sends'],
            reliability: ['Edge gateway keeps external channel boundary visible', 'Connected to inbox and queue', 'Fan-out path is animated'],
            related: ['Unified Inbox', 'Message Queue'],
        },
        connections: ['unified-inbox', 'message-queue'],
    },
    {
        id: 'facebook-channel',
        name: 'Facebook Channel',
        kind: 'channel',
        tier: 'edge',
        status: 'operational',
        shape: 'gateway',
        clusterId: 'communications',
        position: [-570, 0, 250],
        size: [46, 56, 46],
        color: '#1877f2',
        accentColor: '#dfeeff',
        summary: 'Facebook messaging connection for customer conversations and outbound replies.',
        details: {
            purpose: 'Extends the inbox to another customer contact surface.',
            systemRole: 'Messaging platform target for send-message worker.',
            flows: ['Receives routed replies', 'Participates in campaign fan-out', 'Stays grouped with other channel gateways'],
            reliability: ['Edge placement communicates external dependency', 'Queue-backed sends avoid direct coupling', 'Monitoring watches delivery behavior'],
            related: ['Unified Inbox', 'Message Queue', 'Broadcast Campaigns'],
        },
        connections: ['unified-inbox', 'message-queue', 'broadcast-campaigns'],
    },
    {
        id: 'instagram-channel',
        name: 'Instagram Channel',
        kind: 'channel',
        tier: 'edge',
        status: 'operational',
        shape: 'gateway',
        clusterId: 'communications',
        position: [-485, 0, 305],
        size: [46, 56, 46],
        color: '#e1306c',
        accentColor: '#ffe1eb',
        summary: 'Instagram messaging connection for customer conversations and campaign reach.',
        details: {
            purpose: 'Keeps social conversation channels in one operational view.',
            systemRole: 'Messaging platform target for send-message worker and campaigns.',
            flows: ['Receives routed replies', 'Receives campaign sends', 'Feeds visibility into unified operations'],
            reliability: ['Grouped with other social gateways', 'Queue-backed to absorb delivery variability', 'Visible route to campaign district'],
            related: ['Unified Inbox', 'Message Queue', 'Broadcast Campaigns'],
        },
        connections: ['unified-inbox', 'message-queue', 'broadcast-campaigns'],
    },
    {
        id: 'lazada-channel',
        name: 'Lazada Channel',
        kind: 'channel',
        tier: 'edge',
        status: 'operational',
        shape: 'gateway',
        clusterId: 'communications',
        position: [-650, 0, 78],
        size: [50, 58, 50],
        color: '#263f9b',
        accentColor: '#ff7a18',
        summary: 'Commerce channel route for marketplace conversations and operational handoff.',
        details: {
            purpose: 'Brings marketplace customer messages into the same operating view as chat channels.',
            systemRole: 'External commerce channel feeding the unified inbox and outbound message queue.',
            flows: ['Receives marketplace messages', 'Routes customer context into the inbox', 'Keeps commerce conversations aligned with operators'],
            reliability: ['Dedicated edge building keeps marketplace dependency visible', 'Inbound arcs show messages flowing into the inbox', 'Queue-backed sends avoid direct coupling'],
            related: ['Unified Inbox', 'Message Queue', 'Partner Exchange'],
        },
        connections: ['unified-inbox', 'message-queue', 'partner-exchange'],
    },
    {
        id: 'bank-api',
        name: 'Bank API',
        kind: 'integration',
        tier: 'edge',
        status: 'operational',
        shape: 'gateway',
        clusterId: 'integrations',
        position: [-390, 0, -440],
        size: [58, 64, 58],
        color: '#f0b456',
        accentColor: '#fff2d6',
        summary: 'External bank system dependency used by CheckSlip validation.',
        details: {
            purpose: 'Validates slip information against external payment infrastructure.',
            systemRole: 'External integration called by CheckSlip validator.',
            flows: ['Receives validation call', 'Returns verification signal', 'Feeds success or failure notification'],
            reliability: ['Placed outside the owned core to show boundary', 'Connected through CheckSlip validator instead of direct user flow', 'Failure path is routed to notifier'],
            related: ['CheckSlip', 'Notification Hub'],
        },
        connections: ['checkslip', 'notification-hub'],
    },
    {
        id: 'partner-exchange',
        name: 'Partner Exchange',
        kind: 'integration',
        tier: 'edge',
        status: 'operational',
        shape: 'platform',
        clusterId: 'integrations',
        position: [-230, 0, -320],
        size: [76, 54, 70],
        color: '#eec66f',
        accentColor: '#fff4d6',
        summary: 'Partner and legacy connectivity for bookings, sales, inventory, and existing user systems.',
        details: {
            purpose: 'Keeps KaoJai useful in real businesses that already have systems.',
            systemRole: 'Integration layer for partner systems, service A/B/C, and legacy user systems.',
            flows: ['Syncs booking and sales information', 'Links legacy user system paths', 'Keeps external systems at the edge'],
            reliability: ['Exchange yard groups external dependencies', 'Bridge to booking is visible', 'External services remain separated from core data ownership'],
            related: ['Booking Management', 'Bank API', 'Notification Hub'],
        },
        connections: ['booking-management', 'notification-hub'],
    },
    {
        id: 'notification-hub',
        name: 'Notification Hub',
        kind: 'integration',
        tier: 'critical',
        status: 'resilient',
        shape: 'tower',
        clusterId: 'integrations',
        position: [-150, 0, -430],
        size: [58, 82, 58],
        color: '#ff6fa8',
        accentColor: '#ffe5f0',
        summary: 'Alert and notification route for user results, status updates, and CheckSlip verification.',
        details: {
            purpose: 'Closes the loop by returning clear outcomes to users and operators.',
            systemRole: 'Alert and notification service connected to event bus, CheckSlip notifier, and result store.',
            flows: ['Sends success or failure outcomes', 'Routes status updates', 'Receives event bus results'],
            reliability: ['Bright beacon makes user feedback visible', 'Connected to event bus and monitoring', 'Critical path for trust-building updates'],
            related: ['Event Bus', 'CheckSlip', 'Message Queue'],
        },
        connections: ['event-bus', 'checkslip', 'message-queue'],
    },
];

export const entityById = new Map(townEntities.map((entity) => [entity.id, entity]));
